// playgrounds/cloudflare-worker/src/components/orpc-stream.tsx
import { useQuery } from '@tanstack/react-query'
import { orpc } from '../lib/orpc'

export function EventIteratorQueries() {
  const streamed = useQuery(orpc.sse.experimental_streamedOptions({ queryFnOptions: { maxChunks: 3 } }))

  return (
    <div>
      <h2>oRPC and Tanstack Query | Event Iterator example</h2>
      <pre>
        {JSON.stringify(streamed.data, null, 2)}
      </pre>
    </div>
  )
}

// playgrounds/nuxt/app/components/orpc-stream.vue
<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query'

const { $orpc } = useNuxtApp()

const query = useQuery($orpc.sse.experimental_streamedOptions({
  queryFnOptions: { maxChunks: 3 },
}))
</script>

<template>
  <div>
    <h2>oRPC and Tanstack Query | Event Iterator example</h2>
    <pre>
{{ JSON.stringify(query.data.value, null, 2) }}
    </pre>
  </div>
</template>
